# Generated by Django 5.0.3 on 2024-04-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_medication_observations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='frequency',
            field=models.IntegerField(help_text='Número de minutos entre doses', verbose_name='Frequency of Dosage (Minutes)'),
        ),
    ]
